apiVersion: resource.k8s.io/v1beta2
kind: DeviceClass
metadata:
  name: simple-knd
spec:
  selectors:
    - cel:
        expression: device.driver == "simple-knd"
---
apiVersion: resource.k8s.io/v1beta2
kind:  ResourceClaim
metadata:
  name: dra-dummy-interface
spec:
  devices:
    requests:
    - name: dummy
      deviceClassName: dra-dummy-interfaces-class
      selectors:
        - cel:
            expression: device.attributes["simple-knd"].name == "dummy0"
---
apiVersion: v1
kind: Pod
metadata:
  name: pod1
  labels:
    app: pod
spec:
  containers:
  - name: ctr1
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
  resourceClaims:
  - name: dummy1
    resourceClaimName: dra-dummy-interface